-- 04. JOIN, SUBQUERY 실전문제

-- 문제 1. 사원(TEMP)테이블과 부서(DEPT)테이블을 NATURAL JOIN하라 

-- 사원 테이블
SELECT * FROM EMP;
-- 부서 테이블 
SELECT * FROM DEPT;
SELECT * FROM EMP NATURAL JOIN DEPT;

-- 문제 2. 사원번호, 사원이름, 부서이름을 검색하라(EQUI JOIN)
SELECT EMPNO, ENAME, DNAME 
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

-- 문제 3. 사원번호, 사원이름, 부서이름을 검색하라(NATURAL JOIN)
SELECT EMPNO, ENAME, DNAME
FROM EMP NATURAL JOIN DEPT;

-- 문제 4. 사원번호, 사원이름, 부서이름을 검색하라(JOIN ~ USING)
SELECT EMPNO, ENAME, DNAME
FROM EMP JOIN DEPT USING(DEPTNO);

-- 문제 5. 사원번호, 사원이름, 부서이름을 검색하라(JOIN ~ ON)
SELECT EMPNO, ENAME, DNAME
FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;

-- 문제 6. 지역이 NEW YORK인 사원이름을 검색하라(EQUI JOIN)
SELECT ENAME, LOC
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO 
AND LOC = 'NEW YORK';

-- 문제 7. 지역이 NEW YORK인 사원이름을 검색하라(NATURAL JOIN)
SELECT ENAME, LOC
FROM EMP NATURAL JOIN DEPT
WHERE LOC = 'NEW YORK';

-- 문제 8. 지역이 NEW YORK인 사원이름을 검색하라(JOIN USING)
SELECT ENAME, LOC
FROM EMP JOIN DEPT USING(DEPTNO)
WHERE LOC = 'NEW YORK';

-- 문제 9. 지역이 NEW YORK인 사원이름을 검색하라(JOIN ON)
SELECT ENAME, LOC
FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE LOC = 'NEW YORK';

-- 문제 10. 지역이 NEW YORK인 사원의 사원번호, 사원이름을 사원번호 순으로 검색하라.
SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT EMPNO, ENAME, LOC
FROM EMP NATURAL JOIN DEPT
WHERE LOC = 'NEW YORK'
ORDER BY 1;

-- 문제 11. ADAMS 사원이 근무 중인 부서이름과 지역을 검색하라(EQUI JOIN)
SELECT ENAME, DNAME, LOC
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
AND ENAME ='ADAMS';

-- 문제 12. ADAMS 사원이 근무 중인 부서이름과 지역을 검색하라(JOIN ~ USING)
SELECT ENAME, DNAME, LOC
FROM EMP JOIN DEPT USING(DEPTNO)
WHERE ENAME ='ADAMS';

-- 문제 13. ADAMS 사원이 근무 중인 부서이름과 지역을 검색하라(JOIN ~ ON)
SELECT ENAME, DNAME, LOC
FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE ENAME = 'ADAMS';

-- 문제 14. ADAMS 사원이 근무 중인 부서이름과 지역을 검색하라(NATURAL JOIN)
SELECT ENAME, DNAME, LOC
FROM EMP NATURAL JOIN DEPT
WHERE ENAME = 'ADAMS';

-- 문제 15. 급여가 2000 이상인 사원들의 사원명과 지역을 검색하라 
SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT ENAME, SAL, LOC
FROM EMP NATURAL JOIN DEPT
WHERE SAL > 2000;

-- 문제 16. 급여가 1000이상 2000이하인 사원들의 사원번호, 사원이름, 부서이름을 사원번호순으로 검색하라.
SELECT EMPNO, ENAME, DNAME, SAL
FROM EMP NATURAL JOIN DEPT
WHERE SAL >= 1000 AND SAL <= 2000
ORDER BY 1;

SELECT EMPNO, ENAME, DNAME, SAL
FROM EMP NATURAL JOIN DEPT
WHERE SAL BETWEEN 1000 AND 2000
ORDER BY 1;

-- 문제 17. 사원직무가 SALESMAN 이면서 CHICAGO 지역에 근무중인 사원명을 검색하라.
SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT ENAME, JOB, LOC, SAL
FROM EMP NATURAL JOIN DEPT
WHERE JOB = 'SALESMAN' AND LOC = 'CHICAGO';

-- 문제 18. NEW YORK이나 DALLAS 지역에 근무하는 사원들의 사원번호와 사원이름을 사원번호 순으로 검색하라 (EQUI JOIN)
SELECT EMPNO, ENAME, LOC
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
AND (LOC = 'NEW YORK' OR LOC = 'DALLAS')
ORDER BY 1;

SELECT EMPNO, ENAME, LOC
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
AND LOC IN ('NEW YORK', 'DALLAS')
ORDER BY 1;

-- 문제 19. 부서이름이 ACCOUNTING이거나, 지역이 CHICAGO인 사원의 사원번호와 사원이름을 검색하라. (EQUI JOIN)
SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT EMPNO, ENAME, DNAME, LOC
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO 
AND (DNAME = 'ACCOUNTING' OR LOC = 'CHICAGO');

-- 문제 20. NEW YORK이나 DALLAS 지역에 근무하는 사원들의 사원번호와 사원이름을 사원번호 순으로 검색하라. (NATURAL JOIN)
SELECT EMPNO, ENAME, LOC
FROM EMP NATURAL JOIN DEPT
WHERE LOC IN ('NEW YORK', 'DALLAS')
ORDER BY 1;

-- 문제 21. 부서이름이 ACCOUNTING이거나, 지역이 CHICAGO인 사원의 사원번호와 사원이름을 검색하라. (JOIN USING)
SELECT EMPNO, ENAME, DNAME, LOC
FROM EMP JOIN DEPT USING(DEPTNO)
WHERE DNAME = 'ACCOUNTING' OR LOC = 'CHICAGO';

-- 문제 22. 사원번호, 사원이름, 급여, 급여등급을 급여등급별 사원번호 순으로 검색하라.
SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;

SELECT EMPNO, ENAME, SAL, GRADE
FROM EMP, SALGRADE
WHERE SAL BETWEEN LOSAL AND HISAL
ORDER BY 4,1;

-- 문제 23. 사원번호, 사원이름, 상급자사원번호, 상급자이름을 검색하라 (EQUI JOIN)
SELECT A.EMPNO AS 사원번호, A.ENAME AS 사원이름, B.EMPNO AS 상급자사원번호, B.ENAME AS 상급자이름
FROM EMP A, EMP B
WHERE A.MGR = B.EMPNO;

-- 문제 24. 사원번호, 사원이름, 상급자사원번호, 상급자이름을 검색하라 (JOIN  ON)
SELECT A.EMPNO AS 사원번호, A.ENAME AS 사원이름, B.EMPNO AS 상급자사원번호, B.ENAME AS 상급자이름
FROM EMP A JOIN EMP B ON A.MGR = B.EMPNO;

-- 문제 25. BLAKE 사원보다 많은 급여를 받는 사원이름을 검색하라(SUB QUERY)
SELECT ENAME, SAL
FROM EMP 
WHERE SAL > 
    (SELECT SAL 
    FROM EMP 
    WHERE ENAME = 'BLAKE');
    
-- 문제 26. BLAKE 사원보다 많은 급여를 받는 사원이름을 겁색하라(SELF JOIN)
SELECT B.ENAME, B.SAL
FROM EMP A, EMP B
WHERE B.SAL > A.SAL
    AND A.ENAME = 'BLAKE';
    
-- 문제 27. FORD 사원과 같은 부서에 근무하는 사원이름을 검색하라.
SELECT ENAME, DEPTNO FROM EMP
WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'FORD');

-- 문제 28. FORD 사원과 같은 급여를 받는 사원의 사원번호를 검색하라.
SELECT EMPNO, ENAME, SAL FROM EMP
WHERE SAL = (SELECT SAL FROM EMP WHERE ENAME = 'FORD');

-- 문제 29. 부서별 인원수를 부서이름과 함께 사원이 많은 부서 순으로 검색하라.
SELECT DNAME, COUNT(*)
FROM EMP NATURAL JOIN DEPT
GROUP BY DNAME
ORDER BY 2 DESC;

-- 문제 30. 사원번호, 사원이름을 부하직원수가 많은 순으로 검색하라.
SELECT B.EMPNO, B.ENAME, COUNT(*)
FROM EMP A JOIN EMP B ON A.MGR = B.EMPNO
GROUP BY B.EMPNO, B.ENAME, A.MGR
ORDER BY 3 DESC;

-- 문제 31. 부서이름이 'SALES'이면서 사원직무가 'MANAGER'인 사원의 사원번호, 사원이름을 사원이름 순으로 검색하라.
SELECT EMPNO, ENAME, DNAME, JOB
FROM EMP NATURAL JOIN DEPT
WHERE DNAME = 'SALES' AND JOB = 'MANAGER';

-- 문제 32. SCOTT 사원보다 많은 급여를 받는 사원 정보를 검색하라.
SELECT * FROM EMP
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'SCOTT');

-- 문제 33. ALLEN 사원보다 적은 급여를 받는 사원 정보를 검색하라.
SELECT * FROM EMP
WHERE SAL < (SELECT SAL FROM EMP WHERE ENAME = 'ALLEN');

-- 문제 34. 20번 부서 사원의 사원직무와 같은 사원직무인 다른 부서의 사원 정보를 검색하라.
SELECT * FROM EMP
WHERE DEPTNO <> 20 
    AND JOB IN 
    (SELECT JOB 
    FROM EMP 
    WHERE DEPTNO = 20);

-- 문제 35. 전체 사원의 평균 급여보다 급여가 많은 사원정보를 검색하라.
SELECT * FROM EMP
WHERE SAL > (SELECT AVG(SAL) FROM EMP);

-- 문제 36. 급여가 모든 부서들의 평균 급여보다 많은 사원 정보를 검색하라.
SELECT * FROM EMP
WHERE SAL > ALL
    (SELECT AVG(SAL) 
        FROM EMP 
        GROUP BY DEPTNO);
        
-- 문제 37. 20번 부서의 최대 급여보다 최대급여가 큰 부서의 번호와 최대 급여를 검색하라.
SELECT DEPTNO, MAX(SAL)
FROM EMP
WHERE SAL > 
    (SELECT MAX(SAL)
     FROM EMP 
     GROUP BY DEPTNO
     HAVING DEPTNO = 20)
GROUP BY DEPTNO;


