-- 05. 데이터 갱신과 트랜잭션 제어
-- 연습문제 (홀수)

CREATE TABLE STUDENT1
AS SELECT * FROM STUDENT WHERE STU_GRADE IN (1,2);

CREATE TABLE SUBJECT1
AS SELECT * FROM SUBJECT;

CREATE TABLE ENROL1
AS SELECT * FROM ENROL;

-- Q1. 
INSERT INTO STUDENT1 VALUES (20101059, '조병준', '컴퓨터정보', 1, 'B', NULL, 164, 70);
-- (STU_NO, STU_NAME, STU_DEPT, STU_GRADE, STU_CLASS, STU_GENDER)
-- Q3.
INSERT INTO STUDENT1(STU_NO, STU_NAME, STU_DEPT, STU_GRADE, STU_CLASS, STU_GENDER)
    VALUES(20103009, '박소신', '기계', 
        (SELECT STU_GRADE FROM STUDENT1 WHERE STU_NO = 20151062),
        (SELECT STU_CLASS FROM STUDENT1 WHERE STU_NO = 20151062),'M');
        
-- Q5.
UPDATE STUDENT1
SET STU_CLASS = 'B'
WHERE STU_NO = 20153075;

-- Q7. 
UPDATE STUDENT1
SET STU_GRADE = STU_GRADE + 1;

-- Q9. 
UPDATE ENROL1
SET ENR_GRADE = ENR_GRADE + 10
WHERE SUB_NO = (SELECT SUB_NO 
    FROM SUBJECT1 
    WHERE SUB_NAME = '전자회로실험');
    
-- Q11. 
DELETE FROM STUDENT1
WHERE STU_NO = 20143054;


-- Q13. 
UPDATE SUBJECT1
SET SUB_NO = 501
WHERE SUB_NO = 101;

-- Q15.
UPDATE ENROL1
SET SUB_NO = 999
WHERE SUB_NO NOT IN (SELECT SUB_NO FROM ENROL1);

-- Q17. 
DELETE FROM ENROL1
WHERE SUB_NO = 999;

-- Q19.
DELETE FROM SUBJECT1
WHERE SUB_NO NOT IN (SELECT SUB_NO FROM ENROL1); 
